### ISSUE TITLE
Adding maven dependency JUnit 5

### ISSUE THREAD

**Issue by R3dError** [itestra-Passau/SoftwareAnalysisChallenge#1]
We would like to add tests of our implementation using JUnit5.

Are we allowed to modify the file `Implementation/pom.xml` in our own repository to add JUnit 5 as a dependency?
Could modifying the `pom.xml` file or adding test classes interfere with the tests that are run on our submissions later on? (I assume you will check the correctness of our submissions using tests as well.)

**Comment by itestraCKE** [comment]
Yes you are allowed to do so for the case of JUnit
