### ISSUE TITLE
Bonus task getter characterization

### ISSUE THREAD

**Issue by R3dError** [itestra-Passau/SoftwareAnalysisChallenge#2]
The bonus task requires the detection of getter code blocks.
The following pattern is given:
```java
public <...> get<...>(){
    return (this.)?<...>;
}
```
Our questions:
1. Do whitespaces matter in this pattern? Specifically, should all line breaks and all spaces match and should there be no space in front of `{` and four spaces in front of `return`? For example, should the following example be considered as a getter?
```java
public
                
                   int     getNumber     
  (       )                     {
    return

 number     ;      }
```

3. The task says that `<...>` "can be anything". Does that include whitespaces? Specifically, are the following examples considered getters (note the `static` in the first example and the spaces in the type `List    <     Integer     >` in the second example)?
```java
public static int getNumber(){
    return number;
}

public List    <     Integer     > getNumbers(){
    return numbers;
}
```

4. What if the last `<...>` is not a single identifier, but an entire expression, like in the following examples?
```java
public int getMax(){
    return a > b ? a : b;
}

public int getSize(){
    return this.list.size();
}

public int getValue(){
    return switch(state) {
        case S1 -> 0;
        case S2 -> 5;
        default -> -1;
    };
}
```

**Comment by itestraCKE** [comment]
The 80/20 rule applies here, so it would be sufficient if you can detect matching blocks, withoutwhitespaces, as they will probably rarly appear in the real world. But if your implementation can also detect your example, it's even better :)

For question 4: We only cover simple getters. The example would also be counted as SLoC

**Comment by R3dError** [comment]
`1. 3. 4.`
Great counting from my side :facepalm:
