### ISSUE TITLE
Question: naming of files

### ISSUE THREAD

**Issue by schmi552** [itestra-Passau/SoftwareAnalysisChallenge#5]
I have a small question regarding the naming of the files in the output.
We implemented it in a way that the path to the file is the prefix to the key in the output, so the key for the output of file.java would be  /path/to/file.java. In our opinion this ensures that keys are unique and improves findability of a file for e.g. verifying the results.
Is that alright or should just the name of the file (file.java) be the key in the output?
Thanks in advance for the answer.

Kind regards
Johannes

**Comment by itestraCKE** [comment]
Hi Johannes,
sorry for the late reply, but either way would be fine
